"""Editorial reconciliation of each original left-column content bullet.

Keys are PDF page / bullet number in specification-pages.json. Values refer to
stable learning-point keys, with * selecting an explicitly authored family.
This map is checked against source extraction, not used to generate the source list.
"""

CONTENT_MAP = {
    15: [
        'learning-stage-*',
        'learning-feedback practice-whole practice-part practice-variable practice-fixed practice-massed practice-distributed practice-random practice-investigation practice-selection',
        'practice-principle-* practice-session-design practice-schedule-design practice-evaluation',
        'skill-refinement',
        'tactical-decisions',
        'skill-class-*',
        'skilled-performance-*',
        'newton-*',
        'skill-analysis-tool-* skill-critical-analysis',
        'movement-economy',
        'skill-creativity',
    ],
    16: [
        'group-performance',
        'aesthetic-artistic-criteria aesthetic-comparison',
        'choreography-analysis',
        'cardiovascular-function respiratory-function cardiorespiratory-integration',
        'heart-rate-response breathing-response temperature-response body-response-investigation',
        'life-stage-*',
        'activity-benefit-* life-stage-*',
    ],
    17: [
        'fitness-categories fitness-component-*',
        'fitness-needs-analysis fitness-component-*',
        'fitness-test-selection fitness-test-data fitness-component-*',
        'fitness-test-validity fitness-test-reliability',
        'training-method-*',
        'training-principle-* training-programme-design',
        'fitt-* training-programme-design',
        'recovery-strategies overtraining',
        'periodisation',
        'periodised-plan',
        'psychological-factor-*',
        'psychological-assessment-*',
        'psychological-strategy-*',
        'feedback-*',
    ],
    18: [
        'psychological-data-to-goals psychological-action-plan psychological-plan-evaluation',
        'nutrient-* hydration',
        'nutrition-before nutrition-during nutrition-after',
        'nutrition-plan',
        'supplement-*',
        'energy-system-atp-pc energy-system-anaerobic-lactic energy-system-aerobic',
        'energy-system-* energy-systems-preparation',
        'movement-muscles movement-bones joint-actions joint-action-*',
        'muscular-functions skeletal-functions',
        'planes-axes anatomical-plane-*',
        'performance-factors',
        'performance-baseline',
        'performance-goals',
        'performance-improvement-plan',
        'programme-effectiveness',
        'performance-communication',
        'high-performance-pathways',
        'underage-development',
        'sport-ireland governing-bodies',
    ],
    19: [
        'activity-rules safe-event',
        'safety-regulations safe-event',
        'warm-up cool-down',
        'safe-attire safe-equipment safe-facilities',
        'activity-structures activity-tactics composition-elements strategy-transfer',
        'official-readiness-*',
        'official-characteristics',
        'official-communication',
        'official-conflict',
        'coach-knowledge-*',
        'coach-guidance',
        'coach-reflection',
        'ethics-* codes-of-ethics ethical-influences',
        'sportsmanship gamesmanship',
    ],
    20: [
        'doping-categories',
        'doping-performer doping-sport',
        'irish-anti-doping',
        'therapeutic-use-exemption',
        'technology-impact-*',
        'technology-performance',
        'personal-technology',
        'media-participation',
        'media-body-image',
        'sponsorship-messages',
        'media-coverage-strategies',
        'participation-barriers participation-supports lifelong-participation',
        'participation-measurement',
        'participation-promotion',
        'lifestyle-activity',
        'cultural-attitudes cultural-values cultural-traditions',
        'gender-stereotyping',
        'adapted-activity',
        'participation-imbalance',
        'promotion-barrier-response promotion-evaluation-design',
        'school-community-pathways',
        'mass-participation-events',
    ],
}

# Named terms must be present in the original page text and linked to the
# correct explicitly authored requirement; do not derive these from the cards.
NAMED_FAMILIES = [
    (15, 'learning-stage', [('beginner','beginner'),('intermediate','intermediate'),('advanced','advanced')]),
    (15, 'practice', [(x,x) for x in ['whole','part','variable','fixed','massed','distributed','random']]),
    (15, 'practice-principle', [('variety','variety'),('progressive','progressive'),('specific','specific'),
         ('measurable','measurable'),('achievable','achievable'),('realistic','realistic'),('time','time'),
         ('exciting','exciting'),('challenging','challenging'),('recorded','recorded')]),
    (15, 'skill-class', [(x.replace(' ','-'),x) for x in ['gross','fine','open','closed','discrete','serial','continuous','internally paced','externally paced']]),
    (15, 'skilled-performance', [('kinaesthetic-awareness','kinaesthetic awareness'),('anticipation','anticipation'),('consistency','consistency'),('accuracy','accuracy')]),
    (15, 'newton', [('inertia','inertia'),('acceleration','acceleration'),('action-reaction','action/reaction')]),
    (15, 'skill-analysis-tool', [('checklist','checklists'),('coaching-points','coaching points'),('video','video'),('model','model performers')]),
    (16, 'life-stage', [(x.replace(' ','-'),x) for x in ['infancy','childhood','adolescence','adulthood','older adulthood']]),
    (16, 'activity-benefit', [('physical','physical health'),('mental','mental health'),('social','social'),('economic','economic')]),
    (17, 'training-method', [('continuous','continuous'),('interval','interval'),('fartlek','fartlek'),('circuit','circuit'),
         ('resistance','resistance'),('plyometric','plyometrics'),('stretching','stretching')]),
    (17, 'training-principle', [(x.replace(' ','-'),x) for x in ['readiness','specificity','progressive overload','rest','recovery','reversibility','tedium']]),
    (17, 'fitt', [(x,x) for x in ['frequency','intensity','time','type']]),
    (17, 'psychological-factor', [(x,x) for x in ['confidence','anxiety','motivation','concentration']]),
    (17, 'psychological-assessment', [('self-assessment','self-assessment'),('observation','observational'),('interview','interview'),('questionnaire','questionnaires')]),
    (17, 'psychological-strategy', [('goal-setting','goal setting'),('self-talk','self-talk'),('thought-stopping','thought stopping'),
         ('visualisation','visualisation'),('relaxation','relaxation'),('routine','performance routines')]),
    (17, 'feedback', [('intrinsic','intrinsic'),('extrinsic','extrinsic'),('results','knowledge of results'),('performance','knowledge of performance'),
         ('concurrent','concurrent'),('terminal','terminal'),('positive','positive'),('negative','negative')]),
    (18, 'supplement', [(x.replace(' ','-'),x) for x in ['caffeine','creatine','nitrate','beta-alanine','sodium bicarbonate']]),
    (18, 'energy-system', [('atp-pc','ATP-PC'),('anaerobic-lactic','anaerobic lactic'),('aerobic','aerobic')]),
    (19, 'official-readiness', [('knowledge','knowledge'),('fitness','physical fitness'),('psychological','psychological readiness'),('attire','attire'),('equipment','equipment')]),
    (19, 'coach-knowledge', [('physical','physical'),('personal','personal'),('technical','technical')]),
    (19, 'ethics', [(x,x) for x in ['integrity','respect','fairness','equity']]),
    (20, 'technology-impact', [('performer','performers'),('coach','coaches/choreographers'),('official','officials'),('spectator','spectators')]),
]
