"""Validated, pipeline-owned exam information used by the Exam Info modal.

Exam information is small and authoritative, so it is stored as reviewed JSON rather than
generated by a model.  The publication gate requires a complete record and merge renders it
to an additive JavaScript file.  A subject can therefore never publish the empty shell that
previously reached Home Economics.
"""
from __future__ import annotations

import json
from pathlib import Path

from config import CANONICAL

EXAM_INFO_DIR = Path(__file__).parent / "exam-info"


def validate(data, subject: str | None = None) -> list[str]:
    """Return concrete schema errors. An empty list means the record is publishable."""
    errors: list[str] = []
    if not isinstance(data, dict):
        return ["exam info must be a JSON object"]
    if subject and data.get("subject") != subject:
        errors.append(f"subject must be {subject!r}")
    if not isinstance(data.get("subject"), str) or not data.get("subject", "").strip():
        errors.append("subject is required")
    if not isinstance(data.get("totalMarks"), (int, float)) or data.get("totalMarks", 0) <= 0:
        errors.append("totalMarks must be positive")
    if not isinstance(data.get("totalMinutes"), (int, float)) or data.get("totalMinutes", 0) <= 0:
        errors.append("totalMinutes must be positive")
    sections = data.get("sections")
    if not isinstance(sections, list) or not sections:
        errors.append("at least one section is required")
        return errors
    seen: set[str] = set()
    for i, section in enumerate(sections):
        at = f"sections[{i}]"
        if not isinstance(section, dict):
            errors.append(f"{at} must be an object")
            continue
        sid = section.get("id")
        if not isinstance(sid, str) or not sid.strip():
            errors.append(f"{at}.id is required")
        elif sid in seen:
            errors.append(f"{at}.id duplicates {sid!r}")
        else:
            seen.add(sid)
        for field in ("name", "color"):
            if not isinstance(section.get(field), str) or not section.get(field, "").strip():
                errors.append(f"{at}.{field} is required")
        if not isinstance(section.get("marks"), (int, float)) or section.get("marks", 0) <= 0:
            errors.append(f"{at}.marks must be positive")
        tips = section.get("tips")
        if not isinstance(tips, dict):
            errors.append(f"{at}.tips is required")
            continue
        for field in ("timing", "structure"):
            if not isinstance(tips.get(field), str) or not tips.get(field, "").strip():
                errors.append(f"{at}.tips.{field} is required")
        reminders = tips.get("reminders")
        if not isinstance(reminders, list) or not reminders or not all(
                isinstance(x, str) and x.strip() for x in reminders):
            errors.append(f"{at}.tips.reminders must contain non-empty strings")
    return errors


def load(subject: str) -> dict | None:
    path = EXAM_INFO_DIR / f"{subject}.json"
    return json.loads(path.read_text()) if path.exists() else None


def require(subject: str) -> dict:
    data = load(subject)
    errors = validate(data, subject)
    if errors:
        raise ValueError("; ".join(errors))
    return data


def render(subject: str) -> Path:
    """Validate and render an additive JS assignment into the canonical output directory."""
    data = require(subject)
    out = CANONICAL / f"exam-info-{subject}.generated.js"
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    out.write_text(
        "// Generated by pipeline/exam_info.py — edit pipeline/exam-info/"
        f"{subject}.json, not this file.\n"
        "window.EXAM_BREAKDOWN = window.EXAM_BREAKDOWN || {};\n"
        f"window.EXAM_BREAKDOWN[{json.dumps(subject)}] = {payload};\n"
    )
    return out


if __name__ == "__main__":
    import sys
    subj = next((a for a in sys.argv[1:] if not a.startswith("-")), None)
    if not subj:
        raise SystemExit("usage: python3 exam_info.py <subject>")
    try:
        print(render(subj))
    except ValueError as exc:
        raise SystemExit(f"invalid exam info for {subj}: {exc}") from exc
